//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StringKing.StringFunctionInterface {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceTestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceTestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StringKing.StringFunctionInterface.ResourceTestData", typeof(ResourceTestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\windows\system32\AdapterTroubleshooter.exe
        ///C:\windows\system32\aitagent.exe
        ///C:\windows\system32\alg.exe
        ///C:\windows\system32\appidcertstorecheck.exe
        ///C:\windows\system32\appidpolicyconverter.exe
        ///C:\windows\system32\appverif.exe
        ///C:\windows\system32\ARP.EXE
        ///C:\windows\system32\at.exe
        ///C:\windows\system32\AtBroker.exe
        ///C:\windows\system32\atiapfxx.exe
        ///C:\windows\system32\atibtmon.exe
        ///C:\windows\system32\atieclxx.exe
        ///C:\windows\system32\atiesrxx.exe
        ///C:\windows\system32\ATIODCLI.exe
        ///C:\windows\syste [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PathTestData {
            get {
                return ResourceManager.GetString("PathTestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNS
        ///agr64svc
        ///OUTLOOK
        ///svchost
        ///smss
        ///WmiPrvSE
        ///taskhost
        ///mfevtps
        ///services
        ///unsecapp
        ///MSBuild
        ///mcshield
        ///Skype
        ///HPDrvMntSvc
        ///svchost
        ///lsm
        ///WUDFHost
        ///svchost
        ///atieclxx
        ///lsass
        ///csrss
        ///DPAgent
        ///NetworkLicenseServer
        ///jhi_service
        ///LSSrvc
        ///CCC
        ///svchost
        ///dwm
        ///SynTPEnh
        ///hamachi-2
        ///NKRexec
        ///FlashPlayerPlugin_11_3_300_257
        ///INUserInfoClient
        ///svchost
        ///HPFSService
        ///IAStorDataMgrSvc
        ///GoogleCalendarSync
        ///firefox
        ///plugin-container
        ///conhost
        ///TSVNCache
        ///hpCMSrv
        ///InserterEE
        ///svchost
        ///svchost
        ///svchost
        ///dtpd
        ///WLIDSVCM
        ///Udater [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestData {
            get {
                return ResourceManager.GetString("TestData", resourceCulture);
            }
        }
    }
}
