//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StringKingUI.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add input tab.
        /// </summary>
        internal static string AddInputTab {
            get {
                return ResourceManager.GetString("AddInputTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        internal static string AddInputTabShortText {
            get {
                return ResourceManager.GetString("AddInputTabShortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        internal static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste test data.
        /// </summary>
        internal static string InsertTestData {
            get {
                return ResourceManager.GetString("InsertTestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extras.
        /// </summary>
        internal static string MenuExtras {
            get {
                return ResourceManager.GetString("MenuExtras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string MenuInput {
            get {
                return ResourceManager.GetString("MenuInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro.
        /// </summary>
        internal static string MenuMacro {
            get {
                return ResourceManager.GetString("MenuMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        internal static string MenuProgram {
            get {
                return ResourceManager.GetString("MenuProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;.
        /// </summary>
        internal static string MoveTextFromRightToLeft {
            get {
                return ResourceManager.GetString("MoveTextFromRightToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro &apos;{0}&apos; already exists. Overwrite?.
        /// </summary>
        internal static string OverwriteExistingMacroFile {
            get {
                return ResourceManager.GetString("OverwriteExistingMacroFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove input tab.
        /// </summary>
        internal static string RemoveInputTab {
            get {
                return ResourceManager.GetString("RemoveInputTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string RemoveInputTabShortText {
            get {
                return ResourceManager.GetString("RemoveInputTabShortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run macro....
        /// </summary>
        internal static string RunMacroDialog {
            get {
                return ResourceManager.GetString("RunMacroDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info....
        /// </summary>
        internal static string ShowAboutBox {
            get {
                return ResourceManager.GetString("ShowAboutBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start recording.
        /// </summary>
        internal static string StartRecordingMacro {
            get {
                return ResourceManager.GetString("StartRecordingMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop recording.
        /// </summary>
        internal static string StopRecordingMacro {
            get {
                return ResourceManager.GetString("StopRecordingMacro", resourceCulture);
            }
        }
    }
}
