name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      # For MinVer to get git tag
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore StringKing.Functions.sln
    - name: Build
      run: dotnet build StringKing.Functions.sln --configuration Release --no-restore
#    - name: Test
#      run: dotnet test --configuration Release --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
#    - name: Upload coverage to Codecov
#      uses: codecov/codecov-action@v1

    - name: Fetch MinVer version
      run: |
        dotnet new tool-manifest
        dotnet tool install --local minver-cli --version 2.5.0
        echo "MINVER_VERSION=$(dotnet minver -v e)" >> $GITHUB_ENV

    - name: Publish NuGet
      # You may pin to the exact commit or the version.
      # uses: brandedoutcast/publish-nuget@c12b8546b67672ee38ac87bea491ac94a587f7cc
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: StringKing.Functions/StringKing.Functions.csproj
        PACKAGE_NAME: StringKing.Functions
        VERSION_STATIC: ${{ env.MINVER_VERSION }}
        TAG_FORMAT: v*
        NUGET_KEY: ${{ secrets.NUGETORG_APIKEY }}
        # NuGet server uri hosting the packages, defaults to https://api.nuget.org
        NUGET_SOURCE: https://api.nuget.org
        # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
        INCLUDE_SYMBOLS: false
